### ISSUE TITLE
希望增加 上报开关功能

### ISSUE THREAD

**Issue by kinglf** [analysys/ans-android-sdk#5]
欧盟GDPR和工信部 都要求APP 需要 用户同意《事件上报协议 》 之后才可以收集信息和事件。
希望sdk能够增加事件上报/采集 开关 功能，只有用户同意才能进行数据上报

**Comment by nielifeng** [comment]
您好，首先您可以通过控制初始化开关来满足这个需求。

**Comment by nielifeng** [comment]
在新版中已经增加一个发送的开关 ，请你尝试@
